export enum PATH_NAME {
    DASHBOARD = "",
    ACCOUNT = "account",
    PRODUCTS = "products",
    FACTURATION = "facturation",
    GESTION_PERSON = "job",
    GESTION_CUSTOMER = "customer",
    STATS = "stats",
    SUPPORT = "support",
    DOC = "doc",
    CONFIG = "config",
    LOGIN = "Login",
    REGISTER = "Register",
    // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
    HOME = "",
    VITRINE = "Vitrine",
    CHECK_USER_STRIPE_ID = "check-user-stripe-id",
    PAYMENT_STATUS = "payment-status",
    PAYMENT = "payment",
    BOUTIQUE = "boutique",
    RESSOURCE = "ressource",
    BASKET = "basket",
    ADMIN = "auth",
    DETAILS = "details",
    FORGOT_PASSWORD = "forgot-password",
}
