export enum ROLENAME {
  USER = 'USER',
  SUPER_ADMIN = 'SUPER_ADMIN',
  INVOICE = 'INVOICE',
  SUPPORT = 'SUPPORT',
}

export enum ROLENAME_ID {
  USER = 1,
  SUPER_ADMIN = 2,
  INVOICE = 3,
  SUPPORT = 4,
}
