version: '3.7'

services:

  sample:
    container_name: front-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/front-app'
      - '/front-app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true