export enum URL_FRONT {
    DASHBOARD = "",
    ACCOUNT = "account",
    PRODUCTS = "products",
    FACTURATION = "facturation",
    GESTION_PERSON = "job",
    GESTION_CUSTOMER = "customer",
    STATS = "stats",
    SUPPORT = "support",
    DOC = "doc",
    CONFIG_SERVICE = "config",
    LOGIN = "Login",
    REGISTER = "Register",
    HOME = "",
    VITRINE = "Vitrine",
    EMBEDDED_CHECKOUT = "embedded-checkout",
    BOUTIQUE = "Boutique",
    RESSOURCE = "Ressource",
    BASKET = "Basket",
    ADMIN = "Auth",
    DETAILS = "Details",
}

export enum SECTION_NAME {
    DASHBOARD = "Tableau de bord",
    ACCOUNT = "Compte",
    PRODUCTS = "Produits",
    FACTURATION = "Facturation",
    GESTION_PERSON = "Gestion du personnel",
    GESTION_CUSTOMER = "Gestion client",
    STATS = "Statistique",
    SUPPORT = "Service client",
    DOC = "Documentation",
    CONFIG_SERVICE = "Configuration du Service",
    LOGIN = "Login",
    REGISTER = "Register",
    HOME = "",
    VITRINE = "Vitrine",
    BOUTIQUE = "Boutique",
    RESSOURCE = "Ressource",
    Basket = "Basket",
}
