// TODO : Centraliser les url avec les nom de section sous forme de record ou autre pour que les url et intitulé soit lié par paire

export enum URL_FRONT {
    DASHBOARD = "",
    ACCOUNT = "account",
    PRODUCTS = "products",
    FACTURATION = "facturation",
    GESTION_PERSON = "job",
    GESTION_CUSTOMER = "customer",
    STATS = "stats",
    SUPPORT = "support",
    DOC = "doc",
    CONFIG = "config",
    LOGIN = "Login",
    REGISTER = "Register",
    // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
    HOME = "",
    VITRINE = "Vitrine",
    CHECK_USER_STRIPE_ID = "check-user-stripe-id",
    PAYMENT_STATUS = "payment-status",
    PAYMENT = "payment",
    BOUTIQUE = "Boutique",
    RESSOURCE = "Ressource",
    BASKET = "Basket",
    ADMIN = "Auth",
    DETAILS = "Details",
    FORGOT_PASSWORD = "forgot-password",
}

export enum SECTION_NAME {
    DASHBOARD = "Tableau de bord",
    ACCOUNT = "Compte",
    PRODUCTS = "Produits",
    FACTURATION = "Facturation",
    GESTION_PERSON = "Gestion du personnel",
    GESTION_CUSTOMER = "Gestion client",
    STATS = "Statistique",
    SUPPORT = "Service client",
    DOC = "Documentation",
    CONFIG_SERVICE = "Configuration du Service",
    // LOGIN = "Login",
    // REGISTER = "Register",
    // HOME = "",
    VITRINE = "Vitrine",
    BOUTIQUE = "Boutique",
    RESSOURCE = "Ressource",
    // BASKET = "Basket",
}
