name: Publish Docker images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and tag auth-service Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/auth-service:latest ./auth-service
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/auth-service:latest ${{ secrets.DOCKER_HUB_USERNAME }}/auth-service:${{ github.sha }}

      - name: Build and tag front-app Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/front-app:latest ./front-app
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/front-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/front-app:${{ github.sha }}

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/auth-service:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/auth-service:${{ github.sha }}

          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/front-app:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/front-app:${{ github.sha }}
