name: Api-Gateway CI

on:
  push:
    branches: [ "main", "dev",'161-dockerize-app' ]
  pull_request:
    branches: [ "main", "dev",'161-dockerize-app' ]

jobs:
#  lint:
#    if: github.ref == 'refs/heads/dev' || github.event.pull_request.base.ref == 'dev'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '18'
#
#      - name: Install dependencies for api-gateway
#        working-directory: ./api-gateway
#        run: npm install
#
#      - name: Run linter in api-gateway
#        working-directory: ./api-gateway
#        run: npm run lint

  test:
    if: github.ref == 'refs/heads/dev' || github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest
#    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies for api-gateway
        working-directory: ./api-gateway
        run: npm install

      - name: Run tests in auth-service
        working-directory: ./auth-service
        run: npm run test

  build-and-push:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/161-dockerize-app' || github.event.pull_request.base.ref == '161-dockerize-app'
    runs-on: ubuntu-latest
#    needs: [ test ]
#    needs: [ lint, test ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image for api-gateway
        uses: docker/build-push-action@v6
        with:
          context: ./api-gateway
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/api-gateway