name: Delivery-Service CI

on:
  push:
    branches: ['**']
    paths:
      - 'delivery-service/**'
      - '.github/workflows/publish-delivery-service.yml'
  pull_request:
    branches: ['dev', 'main']
    paths:
      - 'delivery-service/**'
      - '.github/workflows/publish-delivery-service.yml'

jobs:
  lint:
    if: >
      (github.event_name == 'push' && github.ref != 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'dev')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps (delivery-service)
        working-directory: .
        run: npm ci

      - name: Run linter (delivery-service)
        working-directory: ./delivery-service
        run: npm run lint

  test:
    if: >
      (github.event_name == 'push' && github.ref != 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'dev')
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps (delivery-service)
        working-directory: ./delivery-service
        run: npm ci

      - name: Run tests (delivery-service)
        working-directory: ./delivery-service
        run: npm run test

  build-and-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # needs: [lint, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image (delivery-service)
        uses: docker/build-push-action@v6
        with:
          context: ./delivery-service
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/delivery-service:latest
