name: Facturation-Service CI

on:
  push:
    branches: ['main', 'dev']
    paths:
      - 'facturation-service/**'
      - '.github/workflows/publish-facturation-service.yml'
  pull_request:
    branches: ['main', 'dev']
    paths:
      - 'facturation-service/**'
      - '.github/workflows/publish-facturation-service.yml'

jobs:
  lint:
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps (facturation-service)
        working-directory: ./facturation-service
        run: npm ci

      - name: Run linter (facturation-service)
        working-directory: ./facturation-service
        run: npm run lint

  test:
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps (facturation-service)
        working-directory: ./facturation-service
        run: npm ci

      # - name: Generate Prisma Client (facturation-service)
      #   working-directory: ./facturation-service
      #   run: npx prisma generate

      - name: Run tests (facturation-service)
        working-directory: ./facturation-service
        run: npm run test

  build-and-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # needs: [lint, test]  # décommente si tu veux forcer la validation préalable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image (facturation-service)
        uses: docker/build-push-action@v6
        with:
          context: ./facturation-service
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/facturation-service:latest
