name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies for auth-service
        working-directory: ./auth-service
        run: npm install

      - name: Run linter in auth-service
        working-directory: ./auth-service
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies for auth-service
        working-directory: ./auth-service
        run: npm install

      - name: Run tests in auth-service
        working-directory: ./auth-service
        run: npm run test


  build:
    runs-on: ubuntu-latest
    needs: lint
#    needs: test
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./auth-service
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/auth-service