name: Front-App CI

on:
  push:
    branches: ['**']
    paths:
      - 'front-app/**'
      - '.github/workflows/publish-front-app.yml'
  pull_request:
    branches: ['dev', 'main']
    paths:
      - 'front-app/**'
      - '.github/workflows/publish-front-app.yml'

jobs:
  lint:
    # Push: toutes les branches SAUF main
    # PR: seulement si la base est dev (feature -> dev)
    if: >
      (github.event_name == 'push' && github.ref != 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'dev')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps (front-app)
        working-directory: ./front-app
        run: npm install

      - name: Run linter (front-app)
        working-directory: ./front-app
        run: npm run lint

  test:
    if: >
      (github.event_name == 'push' && github.ref != 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'dev')
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps (front-app)
        working-directory: ./front-app
        run: npm install

      - name: Run tests (front-app)
        working-directory: ./front-app
        run: npm run jest

  build-and-push:
    # Build Docker UNIQUEMENT sur push vers main (merge dev -> main)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # needs: [lint, test]  # décommente si tu veux forcer la validation préalable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image (front-app)
        uses: docker/build-push-action@v6
        with:
          context: ./front-app
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/front-app:latest
